sudo: required
services:
	- docker

before_install:
	- docker build -t ngochieutran/docker-react -f Dockerfile.dev .

script:
	- docker run -e CI=true ngochieutran/docker-react npm run test -- --coverage
